### Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

In [4]:
arr = np.arange(start=2, stop=50, step=3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [13]:
lst1 = []
lst2 = []
print("Enter elements in first list:")
for i in range(0,5):
    a = int(input())
    lst1.append(a)
print("Enter elements in first list:")
for j in range(0,5):
    b = int(input())
    lst2.append(b)
print("Two list are:",lst1,lst2)
print("List converted array are:\n")
print(np.array(lst1),np.array(lst2))
print("Concatination of array are:")
c = np.concatenate([lst1,lst2])
print(c)
print("Sorted Array is:\n")
c.sort()
print(c)

Enter elements in first list:
1
4
5
7
8
Enter elements in first list:
4
5
6
5
4
Two list are: [1, 4, 5, 7, 8] [4, 5, 6, 5, 4]
List converted array are:

[1 4 5 7 8] [4 5 6 5 4]
Concatination of array are:
[1 4 5 7 8 4 5 6 5 4]
Sorted Array is:

[1 4 4 4 5 5 5 6 7 8]


### Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [19]:
arr = np.arange(0,20).reshape(5,4)
print('Array is:\n',arr)
print('\nArray shape\t',arr.shape)
print('Array dimension\t',arr.ndim)
print('Array size\t',arr.size)

Array is:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Array shape	 (5, 4)
Array dimension	 2
Array size	 20


### Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [29]:
a = np.arange(6)
print(a)

print("\nShape of array\t",a.shape)
print("\nDimrnsion of array is=\t",a.ndim)

print("\nConverted array:\n")
print(a[:,  np.newaxis])
print("\nDimrnsion of array is=\t",a[:, np.newaxis].ndim)
print("\nShape of array is=\t",a[:, np.newaxis].shape)


[0 1 2 3 4 5]

Shape of array	 (6,)

Dimrnsion of array is=	 1

Converted array:

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]

Dimrnsion of array is=	 2

Shape of array is=	 (6, 1)


### Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [31]:
a = np.identity(5)
b = np.ones([5,5])
print('horizontal stacking \n',np.hstack([a,b]),'\n')
print('vertical stacking \n',np.vstack([a,b]))

horizontal stacking 
 [[1. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]] 

vertical stacking 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Questions 6:
How to get unique items and counts of unique items?

In [35]:
a = np.random.randint(20, size = (5,5))
print('Array is \n',a)
b = np.unique(a, return_counts= True)
c = np.vstack([b[0], b[1]])
print('\n Unique values with their count \n',c)

Array is 
 [[ 9  2 18 18  7]
 [ 5  4 14 12 17]
 [ 5 16 10  5  7]
 [ 2  9 19 16  5]
 [ 2 19  4  6  7]]

 Unique values with their count 
 [[ 2  4  5  6  7  9 10 12 14 16 17 18 19]
 [ 3  2  4  1  3  2  1  1  1  2  1  2  2]]
